name: Deploy to EC2 (Docker)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/assignment

            echo "▶ Git pull"
            git pull origin main

            echo "▶ Stop & remove old container"
            docker stop file-ext-blocker || true
            docker rm file-ext-blocker || true

            echo "▶ Build image"
            docker build -t file-ext-blocker -f Dockerfile .

            echo "▶ Run container"
            docker run -d \
              --restart unless-stopped \
              -p 8080:8080 \
              --name file-ext-blocker \
              file-ext-blocker
